modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="Public Domain"
issueTrackerURL="" #optional
[[mods]] #mandatory
modId="wherearemytms" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Where are my TMs [Forge]" #mandatory
logoFile="logo.png" #optional
credits="" #optional
authors="Scouter" #optional

description='''
Adds in TMs for Cobblemon
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.wherearemytms]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.wherearemytms]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.wherearemytms]]
    modId="cobblemon"
    mandatory=true
    versionRange="[1.3.1+1.19.2,)"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.wherearemytms]]
    modId="kotlinforforge"
    mandatory=true
    versionRange="[3,)"
    ordering="BEFORE"
    side="BOTH"
# Change this if you require a certain version of KotlinForForge
